version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_DATABASE: node_auth
      DB_USER: app
      DB_PASSWORD: password
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: node_auth
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  node_app:
    build: .
    ports:
      - 4000:3000
    environment:
      POST: 4000
      DATABASE_URL: mysql://keycloak:password@mysql:3306/keycloak
      KEYCLOAK_URL: http://keycloak:8080/auth
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - keycloak
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
